apiVersion: apps/v1
kind: Deployment
metadata:
  name: reliability-worker
  namespace: reliability
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: reliability-worker
  template:
    metadata:
      labels:
        app: reliability-worker
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: reliability-worker
      containers:
        - name: worker
          image: production-reliability-api:0.1.1
          imagePullPolicy: IfNotPresent
          command:
            - python
            - -m
            - application.worker.order_worker
          env:
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: reliability-config
                  key: REDIS_URL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reliability-worker
  namespace: reliability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: reliability-worker
